### ISSUE TITLE
Idea: Add a Jekyll blog at /blog

### ISSUE THREAD

**Issue by nrobinson2000** [thepracticaldev/1pr#26]
For some reason 1pr seems to be growing into something like dev.to and I am totally okay with this, however I think it would be nice to have a jekyll blog inside of this project, so that we could get to a state where the pull request of the day could be a blog post.

Just an idea.

**Comment by benhalpern** [comment]
I don't want to "waste" PRs on a blog. We're only a few days in, so we'll see where it goes.

In the meantime, I'd love it if we used https://dev.to to tell some of the ongoing stories.. I've given my posts the `1pr` tag (https://dev.to/t/1pr) and I think that could help us keep a canonical sense of the ongoing project heartbeat.

This is obviously me being biased towards our own core product, but I think this could be a great use case for dev.to. I've already gotten a bit confused by #23 #24 and #27 and I think making posts to send signals in the form of dev.to posts about what you're working on could be really helpful.

**Comment by nrobinson2000** [comment]
Totally understood.  I think just using dev.to would be fine.  I was just throwing the idea out there.
